---
title: "Expert Designer"
---

This activity is designed to simulate the environment in which you will be 
working for the weekly Practice Activities. 

## Instructions, Roles, & Rules

Get into groups of four (4) students. Similar to last week's Broken 
Circles activity, each of you has an envelope containing different shapes.

### Designer

In this activity, one person in your group will take on the role of the 
"designer," two members will be the "players," and one person will be the 
"observer." The designer uses every shape in the envelope to create a
design that **is not** shared with anyone else. The designer is then
tasked with instructing the players how to replicate the design they created, but there are some rules. 

1. The designer cannot touch the players shapes. 
2. The designer cannot tell the players how to assemble the shapes into the correct design. 
3. The designer **can** respond to questions posed by the players. 

### Players

"Players" are tasked with solving the design made by the "designer."
Players can pose questions to the designer to uncover their design. Once
an player believes they have figured out the design, the designer should
check their solution. If the designer says the solution is correct, then
the player can assist the designer in answering questions posed by the
other players.

### Observer

The "observer" is tasked with monitoring the interactions between the 
designer and the players. Specifically, the observer should check off the 
number of times they see two behaviors occurring, (1) explaining by 
telling how, and (2) everybody helps. The observer should have a scoring 
sheet to tally the number of times they see each behavior. 
 
## Getting Started

Choose one person in your group to be the first designer. Carry out the 
process described above until every observer has correctly identified the
design. You will have 10-minutes to complete this task. 

Once you have completed this task, if there is still time remaining your 
group should choose a new designer and repeat the process. 

## Discussion

-   What do you think this game was about? What was its purpose?
-   What did your group did that made you cooperate more successfully?
-   What did your group did that made cooperation harder?
-   What are some behaviors that could be implemented in the future to make cooperation easier?

