---
title: "Master Script Data Processing"
format: html
editor: source
execute:
  echo: false
  message: false
  warning: false
  eval: false
---

```{r}
#| label: load-packages
library(tidyverse)
library(lubridate)
library(scales)
```

## Import Data and View

```{r}
#| label: load-data
# loads in data on salaries for data scientists
ds_salaries <- read_csv("data/input_data_files/ds_salaries.csv") |> 
  select(-1)
```

## View Original Data

```{r}
#| label: original-data-view
ds_salaries |> 
  head(50)
```

{{< pagebreak >}}

## Filter Just US Based Jobs

```{r}
#| label: filter-us-jobs
ds_salaries |> 
  filter(company_location == "US") |> 
  filter(employee_residence == "US") |> 
  head(50)
```

{{< pagebreak >}}

## Filter out entry level jobs only

```{r}
#| label: filter-entry-level
ds_salaries |>   
  filter(company_location == "US") |> 
  filter(employee_residence == "US") |> 
  filter(experience_level == "EN") |> 
  head(50)
```

{{< pagebreak >}}

## Count of positions by Remote Work and Company Size

```{r}
ds_salaries |> 
  filter(company_location == "US") |> 
  filter(employee_residence == "US") |> 
  filter(experience_level == "EN") |> 
  count(remote_ratio, company_size)
```

{{< pagebreak >}}

## Graph of Remote Work and Company Size

```{r}
ds_salaries |> 
  filter(company_location == "US") |> 
  filter(employee_residence == "US") |> 
  filter(experience_level == "EN") |> 
  mutate(company_size = fct_relevel(company_size, c("S", "M", "L"))) |> 
  ggplot(aes(x = factor(remote_ratio), fill = fct_rev(company_size))) +
  geom_bar() +
  theme_light() +
  scale_fill_viridis_d(breaks = c("S", "M", "L"),
                       labels = c("Small", "Medium", "Large")) + 
  labs(y = "Number of US-Based Entry Level \n Data Science Positions (n = 29)",
       x = "Ratio of Remote Work (%)",
       fill = "Size of Company",
       title = "US-Based Entry Level Data Science Positions Are Often Remote")
  
```

{{< pagebreak >}}

## Group and Calculate Average Salary by year

```{r}
#| label: calculate-avg-salary
ds_salaries |> 
  filter(company_location == "US") |> 
  filter(employee_residence == "US") |> 
  filter(experience_level == "EN") |> 
  mutate(company_size = fct_relevel(company_size, c("S", "M", "L"))) |> 
  group_by(work_year, company_size) |> 
  summarise(avg_salary_usd = mean(salary_in_usd),
            num_employees = n())

```

{{< pagebreak >}}

```{r}
ds_salaries |>
  filter(company_location == "US") |>
  filter(employee_residence == "US") |>
  filter(experience_level == "EN") |>
  mutate(work_year = lubridate::ymd(work_year, truncated = 2L)) |>
  group_by(work_year, company_size) |>
  summarise(avg_salary_usd = mean(salary_in_usd),
            num_employees = n()) |>
  ggplot(
    aes(
      x = work_year,
      y = avg_salary_usd,
      group = company_size,
      color = company_size,
      shape = company_size
    )
  ) +
  geom_point(size = 3) +
  geom_line(linewidth = 1) + 
  scale_x_date(breaks = breaks_width("1 year"),
               labels = label_date_short(format = "%Y")) +
  scale_y_continuous(labels = scales::label_currency(prefix = "$"),
                     limits = c(62000, 125000)) +
  scale_color_viridis_d(breaks = c("S", "M", "L"),
                        labels = c("Small", "Medium", "Large"),
                        end = 0.85) +
  geom_text(aes(label = paste0("n = ", num_employees),
                vjust = 1.5)) +
  guides(shape = "none") +
  theme_light() +
  labs(
    y = "Average Salary for of US-Based Entry Level \n Data Science Positions (n = 29)",
    x = "Year Salary was Paid",
    color = "Size of Company",
    title = "Large Company Salaries are More Consistent \n for US-Based Entry Level Data Science Positions"
  )

```

```{r}
ds_salaries |> 
  count(employee_residence)

summary_salaries <- ds_salaries |>
  filter(employment_type == "FT") |>
  filter(experience_level == "EN") |>
  mutate(work_year = lubridate::ymd(work_year, truncated = 2L)) |>
  group_by(work_year, company_size) |>
  summarise(avg_salary_usd = mean(salary_in_usd),
            num_employees = n())

ft_en_salaries <- ds_salaries |>
  filter(employment_type == "FT") |>
  filter(experience_level == "EN") |>
  mutate(work_year = lubridate::ymd(work_year, truncated = 2L)) 


ft_en_salaries |> 
  ggplot(
    aes(
      x = work_year,
      color = company_size,
      shape = company_location
    )
  ) +
  geom_point(aes(y = salary_in_usd)) +
  scale_x_date(breaks = breaks_width("1 year"),
               labels = label_date_short(format = "%Y")) +
  scale_y_continuous(labels = scales::label_currency(prefix = "$")) +
  scale_color_viridis_d(breaks = c("S", "M", "L"),
                        labels = c("Small", "Medium", "Large"),
                        end = 0.85) +
  guides(shape = "none") +
  theme_light() +
  labs(
    y = "Average Salary for of US-Based Entry Level \n Data Science Positions (n = 29)",
    x = "Year Salary was Paid",
    color = "Size of Company",
    title = "Large Company Salaries are More Consistent \n for US-Based Entry Level Data Science Positions"
  )
```
